spring:
  redis:
    # redis 地址
    host: 192.168.203.132
    # redis 端口
    port: 6379
    # redis 密码
    password: 123456
    # 第几个数据库
    database: 1
    # 连接池配置
    lettuce:
      pool:
        max-active: 10
        min-idle: 5