spring:
  cloud:
    stream:
      rocketmq:
        binder:
          name-server: 120.25.207.44:9876
      bindings:
        input: {destination: sms-topic-xtl, content-type: application/json, group: sms-group}